# Site settings
title: Manuel Salvadori
description: Manuel Salvadori portfolio website
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Manuel Salvadori
user_description: I am a software developer specialized in game development. I attended master's degree in Computer Science at Università Statale di Milano. My areas of interest are game logic programming, artificial intelligence applied to videogames and real-time graphics. This is my portfolio website with a few project I worked on in the last years.
user_title: Software Developer
email: mailto:morke.bm@hotmail.it
facebook_username: mansalvadori
github_username: manuelsalvadori
linkedin_username: manuel-salvadori-a48b12151

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
